services:
  db:
    image: postgres:16.3
    restart: always
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    env_file:
      - ".env"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 6432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

  api:
    build: service-statuses-app/
    container_name: service-statuses-app
    restart: always
    volumes:
      - ./service-statuses-app:/app
    command: /bin/bash "/app/start.sh"
    ports:
      - 8000:8000
    env_file:
      - ".env"
    environment:
      - APP_CONFIG__DB__URL=${APP_CONFIG__DB__URL}
      - APP_CONFIG__DB__ECHO=${APP_CONFIG__DB__ECHO}
    depends_on:
      db:
        condition: service_healthy
