"""Service and ServiceState models

Revision ID: 7b6d88494391
Revises:
Create Date: 2024-07-16 10:45:29.400063

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7b6d88494391'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('WORK', 'NOT_WORK', 'UNSTABLE', name='servicestatusenum').create(op.get_bind())
    op.create_table(
        'services',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
        sa.UniqueConstraint('name', name=op.f('uq_services_name')),
    )
    op.create_table(
        'service_statuses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'status',
            postgresql.ENUM('WORK', 'NOT_WORK', 'UNSTABLE', name='servicestatusenum', create_type=False),
            nullable=False,
        ),
        sa.Column('start_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('description', sa.String(length=120), nullable=False),
        sa.Column('service_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['service_id'], ['services.id'], name=op.f('fk_service_statuses_service_id_services'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_service_statuses')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_statuses')
    op.drop_table('services')
    sa.Enum('WORK', 'NOT_WORK', 'UNSTABLE', name='servicestatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
